# frozen_string_literal: true

require "bundler/gem_tasks"
require "rspec/core/rake_task"

RSpec::Core::RakeTask.new(:spec)

task default: :spec

desc "Ejecutar las espectativas"
task :test do
  sh "rspec -I spec/granja_rspec.rb"
end